//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "save image",
                apiDescription: "save image",
                paths: [
                 "/items", "/items/123",                ],
                endPoint: "https://pkniamzrp0.execute-api.us-east-1.amazonaws.com/Development",
                apiClient: AWSAPI_PKNIAMZRP0_SaveimageMobileHubClient(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
