//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_SUQe1bVPe"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "k75nv4hud9hrs5doc8p2459n7"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "2pitj45tuolsedn0et8sl8sc4o0d4is74bv4qatcjg3sos68o6q"

// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .USEast1
